name: napari-tomotwin
channels:
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - napari[version='>=0.4.19']
  - pandas
  - numpy
  - pyqt
  - matplotlib
  - scipy
  - scikit-learn
  - tqdm
  - mrcfile
  - cuml=23.12
  - cuda-version=11.8
  - git
  - pip
  - pip:
      - napari-boxmanager # Install napari-boxmanager via pip because otherwise scripts in setup.cfg are ignored
      - git+https://github.com/BiAPoL/napari-clusters-plotter.git@b9b08f3500c9b0831d2cd1b4d9a757c688f76005 #until 0.7.4 is released
