name: napari-tomotwin
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - napari=0.4.18
  - pandas
  - numpy
  - pyqt
  - matplotlib
  - scipy
  - scikit-learn
  - tqdm
  - mrcfile
  - pip:
      - git+https://github.com/BiAPoL/napari-clusters-plotter.git@095d9e8
