name: napari-tomotwin
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - napari=0.4.18
  - pandas
  - numpy
  - pyqt
  - matplotlib
  - scipy
  - scikit-learn
  - pip
  - pip:
    - tqdm
    - napari-clusters-plotter>=0.7.2